name: Install Chromium, Chromium-driver, and Selenium

on:
  push:
    branches:
      - main

jobs:
  install-packages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Update apt-get and install Chromium & Chromium-driver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install Selenium
      run: |
        pip install selenium

    - name: Install BS4 & SQLite3
      run: |
        pip install beautifulsoup4 sqlite3
        
    - name: Download Chromedriver
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip

    - name: Run wine.py
      run: |
        python wine.py
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add wine_data.db
        git commit -m "Add output file from wine.py"
        git push origin main
